### ISSUE TITLE
ClassNotFoundException invoking map-object

### ISSUE THREAD

**Issue by shultzy88** [oakes/play-clj#102]
I have a texture that I want to add to a layer of a loaded map. When `map-object` is invoked the code fails to compile in the REPL and throws a `ClassNotFoundException`, the stack trace shows one line that looks to be the culprit: `com.badlogic.gdx.maps.object.TextureMapObject`. I also tried using `:rectangle` and get the same error but with `RectangleMapObject`.

**Comment by oakes** [comment]
Just fixed in version 1.1.1. Please update your project.clj and let me know if you still see this issue. Thanks!
