### ISSUE TITLE
Check for multiple key presses?

### ISSUE THREAD

**Issue by enragedginger** [oakes/play-clj#109]
I just ran through the tutorial. What's the appropriate way for checking for multiple key presses simultaneously? It looks like the screen map in `:on-key-down` has a `:key` property which only points to a single key (instead of a collection of keys).

**Comment by oakes** [comment]
You may also use the [key-pressed](https://oakes.github.io/play-clj/#core.key-pressed_q.html) function, which you would normally call inside the `:on-render` event.

**Comment by enragedginger** [comment]
Great! Thank you!
