### ISSUE TITLE
Building for HTML5

### ISSUE THREAD

**Issue by donbonifacio** [oakes/play-clj#41]
Hello,

I'm just starting to checkout play-clj. Can I build for HTML too? It seams to be possible from libgdx.

Thanks,

**Comment by typedeph** [comment]
Something like this? http://teavm.org/

**Comment by CaptainLexington** [comment]
+1 - Targeting the web is super important, but I would like to use a robust, production-ready library rather than roll my own if at all possible - and targeting other platforms natively rather than through JavaScript VMs is attractive.
