### ISSUE TITLE
about DOCS page

### ISSUE THREAD

**Issue by ghost** [oakes/play-clj#45]
Ey recently i've been on play-clj DOCS page a lot. And i find the behaviour of the page mighty annoying. Say, i wanna look at --> play-clj.math section --> i scroll to it --> open vector-3 for example --> and immediately the whole list scrolls all the way up. Means that i have to open each page to a new tab OR i have to keep scrolling the list just so i can return to the section i was just looking at. I could possibly come up with some css / js to make it a lil more user-friendly..

**Comment by oakes** [comment]
Fixed via https://github.com/oakes/play-clj/pull/65
