### ISSUE TITLE
Could not find template play-clj on the classpath.

### ISSUE THREAD

**Issue by marco-fiset** [oakes/play-clj#66]
When trying to run `lein new play-clj helloworld`, I get the following error message:

`Could not find template play-clj on the classpath.`

I'm on Mac OS X Yosemite 10.10.

**Comment by oakes** [comment]
Can you try updating Leiningen? I think there was a problem with Leiningen 2.5.0 that occurred when lein-ancient was in your profile. Just my first guess.

**Comment by marco-fiset** [comment]
Thanks, it worked! Should have checked this out before posting here...
