### ISSUE TITLE
Conflicting Symbols Between Project Name and Play-CLJ 

### ISSUE THREAD

**Issue by Yoshiyuka** [oakes/play-clj#69]
While in the process of writing up a separate issue to submit for play-clj I've ran `lein new play-clj dialog` to form a new project where I can demonstrate the minimal code needed to reproduce issues with the dialog ui element. 
As it turns out, this causes symbol conflicts if you name a project the same as any of the existing symbols defined in any of the namespaces in Play-CLJ. 
In my case: `Exception in thread "main" java.lang.IllegalStateException: dialog already refer
s to: #'play-clj.ui/dialog in namespace: dialog.core, compiling:(dialog/core.clj
:16:1)`

This behavior makes sense. However, in the off chance that somebody insists on naming their project as something that's already defined elsewhere, perhaps there can be some name mangling to resolve the conflicts?

**Comment by oakes** [comment]
That is a good idea. This is now fixed via f74c5d7820f5ddd214a8894b724580bba8a12837.
