### ISSUE TITLE
rectangle :contains returns int instead of boolean (always true)

### ISSUE THREAD

**Issue by Antender** [oakes/play-clj#82]

**Comment by oakes** [comment]
Are you sure? In a REPL, I get this:

```clojure
=> (rectangle! (rectangle 0 0 10 10) :contains (rectangle 5 5 10 10))
false
```

**Comment by Antender** [comment]
I tried to use it like this:
(rectangle 
  card-x card-y 
  card-width card-height 
  :contains (game :x) (game :y))

**Comment by oakes** [comment]
Oh yeah that won't work. The `rectangle` macro will always return the rectangle object you are creating, so the return value of any methods you embed in it will be ignored.
