### ISSUE TITLE
Need help , got into trouble from beginning!

### ISSUE THREAD

**Issue by SageHan** [oakes/play-clj#83]
Leiningen 2.5.1 on Java 1.7.0_76 Java HotSpot(TM) 64-Bit Server VM
    OSX 10.10.3 (14D136)

Got this error when try to `lein new paly-clj hello-worl`:

    Failed to resolve version for paly-clj:lein-template:jar:RELEASE: Could not find metadata paly-clj:lein-     template/maven-metadata.xml in local (/Users/ajmj/.m2/repository)
    This could be due to a typo in :dependencies or network issues.
    If you are behind a proxy, try setting the 'http_proxy' environment variable.

I had google so hard, but can't fixed this thorny problem!

**Comment by oakes** [comment]
Looks like it's just a typo. It should be "play-clj", not "paly-clj" =)

**Comment by oakes** [comment]
Let me know if you have other problems.
