### ISSUE TITLE
first-entity and second-entity crash when there are entities without a :body

### ISSUE THREAD

**Issue by scheibenkaes** [oakes/play-clj#91]
Given you have entities with and entities without a :body in the same screen, trying to detect a collision will result in an exception:

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.Exception: The keyword :body is not found.

This is due to find-body using get-obj which throws the key not found exception.

I tried the workarounds:

- assoc'ing :body true on those entities => exception on rendering
- having only simulated entities in this screen, but it's rather inconvenient as I have a texture following an entity with a body

Did I get something wrong or wouldn't be better to ignore those entities without a body in the implementation of first- and second-entity?

**Comment by oakes** [comment]
Yeah that was definitely an oversight. I just fixed it and pushed 1.1.0-SNAPSHOT so you can try it out.

**Comment by scheibenkaes** [comment]
Tried it and the issue is now gone. Thanks for fixing and for this great project in general!
